# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 14:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('published', models.BooleanField(default=0)),
                ('body', models.TextField()),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateField()),
                ('updated_at', models.DateTimeField()),
                ('image', models.CharField(max_length=100)),
                ('image_width', models.IntegerField()),
                ('image_height', models.IntegerField()),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
