# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170824_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'get_latest_by': 'updated_at', 'ordering': ['-updated_at']},
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
