# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blog_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='user_id',
        ),
    ]
