# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(default='Comment', max_length=100),
            preserve_default=False,
        ),
    ]
